version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: globant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/globant_db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

volumes:
  pgdata:
